
* Set up

Make sure you have ~ipython~, ~aiter~, and ~nc~ installed. In a pinch,
you can use ~telnet~ instead of ~nc~.


* An initial trivial server

** Set up the server

ipython

from aiter.server import start_server_aiter
server, aiter = await start_server_aiter(7777)
async for _ in aiter: print(_)

or

ipython -c "from aiter.server import start_server_aiter; s, a = await start_server_aiter(7777); [print(_) async for _ in a]"

** Connect to it

In another terminal, do the following:

nc localhost 7777

then hit control-C. Then do it a few more times.

On each connection, you'll see an ordered pair (r, w) where r is a StreamReader and w is a StreamWriter.

** Exit cleanly

Now try the following:

#+BEGIN_SRC python
from aiter.server import start_server_aiter
server, aiter = await start_server_aiter(7777)
count = 0
async for _ in aiter:
    print(_)
    count += 1
    if count >= 3:
        server.close()
#+END_SRC


This will accept three connections, then close the server.

Try launching it and connecting. After the third connection, the server will simply exit. No need explicitly break from the loop.


* Handling Clients

It's easy to extract framed bytes out of a StreamReader and turn them into messages.

Here is code that turns a StreamReader into an aiter of readline messages.

#+BEGIN_SRC python
async def stream_reader_to_line_aiter(sr):
    while True:
        r = await sr.readline()
        if len(r) == 0:
            break
        yield r
#+END_SRC

It's pretty easy to see how this could be adapted for more complex message formats, either text or binary.

Now try ~examples/2-line-server.py~. This accepts a single connection, then accepts messages terminated with a "\n"
character, and echos them. Try connecting with ~nc~ and type a few lines. Then exit with control-C (harsh exit) or
control-D (clean exit). You'll see that the server exits cleanly, indicating that the ~line_aiter~ completed. The
error and the clean exit code paths are the same.


server => aiter of (StreamReader, StreamWriter)

(StreamReader, StreamWriter) => aiter of (message, StreamWriter)

So we see how we can turn

aiter of (StreamReader, StreamWriter) => aiter of (aiter of (message, StreamWriter))

So we have an aiter of aiters. Whenever you see this construct, the thing you want is a ~join_aiter~.
This turns an aiter of aiters into a single aiter that is a union of the objects coming out of each constituent
aiter.

This gives us a transformation from

aiter of (StreamReader, StreamWriter) => aiter (message, StreamWriter)

Now we see we can write one method to handle streams from *all* clients at once.

See ~examples/3-multi-client-server.py~
